name: GUIPlugin
version: ${project.version}
main: com.miketheshadow.guiplugin.GUIPlugin
api-version: 1.13
depend: [NBTAPI,ComplexProficiencies]
authors: [MikeTheShadow]
commands:
  guiadd:
    description: Adds a gui
    usage: /<guiadd> [GUIName]
    permission: GUIPlugin.admin
    permission-message: You don't have GUIPlugin.admin permission
  guiopen:
    description: Displays a crafting gui
    usage: /<guiopen> [player] [guiname] (use if adding recipes ->) [levelReq] [laborCost] [moneyCost] [profession]
    permission: GUIPlugin.gui
    permission-message: You don't have GUIPlugin.gui permission